/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.cardiffmet.st20128572.timeline;

import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom2.JDOMException;

/**
 *
 * @author John
 */
public class EventViewer extends javax.swing.JFrame {

    Event e;
    static List <Person> peopleArray;
    /**
     * Creates new form EventViewer
     * @param e The Event object being displayed.
     */
    public EventViewer(Event e) {
        this.e = e;
        
        initComponents();
        addBtn.setVisible(false);
        cancelBtn.setVisible(false);
        name.setText(e.getTitle());
        people.setText(e.listPeople());
        description.setText(e.getDescription());
        dob.setText(e.getDate());
        setTitle(e.getTitle());
        peopleArray = new ArrayList<>();
        if(e.getTitle() == "")
        {
            editName.setVisible(false);
            editDOB.setVisible(false);
            //addPeopleToEventBtn.setVisible(false);
            editDesc.setVisible(false);
       
            addBtn.setVisible(true);
            cancelBtn.setVisible(true);
        }
        
    }
    
    public static void setPeople(List<Person> newPeople)
    {
        
        peopleArray = newPeople;
    }
    
    public List<Person> getPoi()
    {
     
        return peopleArray;
    }
    
    
    public List<Person> peopleArray()
    {
        return peopleArray;
    }
    
    public GregorianCalendar fromString(String date) throws ParseException
    {
        String[] parts = date.split("-");
        int day = Integer.parseInt(parts[0]);
        int month = convertMonth(parts[1]);
        int year = Integer.parseInt(parts[2]);
        
        return new GregorianCalendar(year, month, day);
    }
    
    
    
    public String dateToString(GregorianCalendar date)
    {
        Date d = date.getTime();
        DateFormat df = DateFormat.getDateInstance();
        String dateS = df.format(d);
        return dateS;
    }
    
    
    public int convertMonth(String month)
    {
        int newMonth;
        
        switch(month)
        {
            case "Jan": newMonth = 0;
            break;
            case "Feb": newMonth = 1;
            break;
            case "Mar": newMonth = 2;
            break;
            case "Apr": newMonth = 3;
            break;
            case "May": newMonth = 4;
            break;
            case "Jun": newMonth = 5;
            break;
            case "Jul": newMonth = 6;
            break;
            case "Aug": newMonth = 7;
            break;
            case "Sep": newMonth = 8;
            break;
            case "Oct": newMonth = 9;
            break;
            case "Nov": newMonth = 10;
            break;
            case "Dec": newMonth = 11;
            break;
            
            default: newMonth = 0;
        }
        
        return newMonth;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        editName = new javax.swing.JButton();
        editDOB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addPeopleToEventBtn = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        editDesc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        dob = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        people = new javax.swing.JLabel();
        hiddenPoiValues = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("People Involved");

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        jScrollPane1.setViewportView(description);

        editName.setText("Edit");

        editDOB.setText("Edit");

        jLabel1.setText("Title");

        addPeopleToEventBtn.setText("Add People");
        addPeopleToEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPeopleToEventBtnActionPerformed(evt);
            }
        });

        name.setText("jTextField1");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        editDesc.setText("Edit");

        jLabel2.setText("Date");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        dob.setText("jTextField1");
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        jLabel3.setText("Description");

        people.setText("Blank");

        hiddenPoiValues.setVisible(false);
        hiddenPoiValues.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editDOB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addPeopleToEventBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hiddenPoiValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(editDesc)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDOB))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPeopleToEventBtn)
                    .addComponent(people))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(hiddenPoiValues))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
    public void run() 
            {
                new EventViewer(e).setVisible(true);
            }
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String newDescription = description.getText();
        GregorianCalendar newDOB = new GregorianCalendar(1970,0,1);
        String newName = name.getText();
        List<Person> poi = getPoi();
        
        //String newDOB = 
        try
        {
            newDOB = fromString(dob.getText());
        }
        catch (ParseException ex)
        {
            Logger.getLogger(Bio.class.getName()).log(Level.SEVERE, null, ex);
            //ErrorMessage e = new ErrorMessage("Invalid date");
            //e.run();
        }

        Data d = new Data();
        XMLReadWrite x = new XMLReadWrite();

        d.addEvent(d.events, newDescription, newDOB, newName, poi);
        try
        {
            x.writeEventXML(newDescription, dateToString(newDOB), newName, poi);
        }
        catch (JDOMException | IOException ex)
        {
            Logger.getLogger(Bio.class.getName()).log(Level.SEVERE, null, ex);
        }

        EventTableModel model = new EventTableModel();
        MainMenu.eventTable.setModel(model);
        
       
        MainMenu.timelinePanel = new Timeline();
        MainMenu.timelinePanel.repaint();
        MainMenu.btnPanel = new ButtonPanel();
        //MainMenu.btnPanel.addBtns();
        this.dispose();
        

    }//GEN-LAST:event_addBtnActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void addPeopleToEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPeopleToEventBtnActionPerformed
       AddPersonToEvent aPTE = new AddPersonToEvent();
       aPTE.run();
    }//GEN-LAST:event_addPeopleToEventBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addBtn;
    public javax.swing.JButton addPeopleToEventBtn;
    public javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField dob;
    public javax.swing.JButton editDOB;
    public javax.swing.JButton editDesc;
    public javax.swing.JButton editName;
    public static javax.swing.JLabel hiddenPoiValues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    public static javax.swing.JLabel people;
    // End of variables declaration//GEN-END:variables
}
